name: Terraform Lint

on:
  push:
    paths:
      - "terraform/**/*"

jobs:
  lint:
    runs-on: macos
    steps:
      - uses: actions/checkout@v1
      - run: brew install terraform@0.11 tflint
      - name: tflint
        run: |
          cd terraform
          tflint .
